In [19]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline  

In [ ]:
duffy_data=pd.read_csv('duffy_data.csv')

In [ ]:
duffy_data.head()

In [22]:
duffy_data.describe()

ID  Cost per load        Dist  Lead time(days)  \
count  100.000000     100.000000   100.00000        100.00000   
mean    50.500000    3131.600000  1207.18000          5.87000   
std     29.011492     655.358519   386.84242          3.96106   
min      1.000000    1660.000000   502.00000          0.00000   
25%     25.750000    2631.750000   904.00000          2.75000   
50%     50.500000    3166.000000  1273.00000          6.00000   
75%     75.250000    3701.250000  1538.25000          9.00000   
max    100.000000    4301.000000  1793.00000         13.00000   

       Trailer length(feet)       Wgt(Lb)  Unnamed: 7  Unnamed: 8  Unnamed: 9  
count            100.000000    100.000000         0.0         0.0         0.0  
mean              51.250000  26708.180000         NaN         NaN         NaN  
std                2.396862   7069.840196         NaN         NaN         NaN  
min               48.000000  15100.000000         NaN         NaN         NaN  
25%               48.000000  21220.750000         NaN         NaN         NaN  
50%               53.000000  26513.500000         NaN         NaN         NaN  
75%               53.000000  32276.000000         NaN         NaN         NaN  
max               53.000000  39931.000000         NaN         NaN         NaN

In [36]:
Corr_CPL_and_Wgt = np.corrcoef(duffy_data['Cost per load'],duffy_data['Wgt(Lb)'])

Corr_CPL_and_Dist = np.corrcoef(duffy_data['Cost per load'],duffy_data['Dist'])

Corr_CPL_and_leadtime = np.corrcoef(duffy_data['Cost per load'],duffy_data['Lead time(days)'])

Corr_CPL_and_leadtime = np.corrcoef(duffy_data['Cost per load'],duffy_data['Lead time(days)'])


### Relation between Cost Per Load of truck and Weight (Lb)

In [29]:
Corr_CPL_and_Wgt

array([[1.        , 0.90421307],
       [0.90421307, 1.        ]])

### Relation between Cost Per Load of truck and Distance (miles)

In [33]:
Corr_CPL_and_Dist

array([[1.        , 0.90421307],
       [0.90421307, 1.        ]])

### Relation between Cost Per Load of truck and Leadtime (days)

In [34]:
Corr_CPL_and_leadtime

array([[ 1.        , -0.09331368],
       [-0.09331368,  1.        ]])